

import { Inter } from 'next/font/google'
import './globals.css'
import Header from './companent/Header'
import Provider from './companent/Provider'
import Tabs from './companent/Tabs'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MovieApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider enableSystem={true} attribute="class" >
        <Header/>
        <Tabs/>
        {children}
        </Provider>
        </body>
    </html>
  )
}
